import React, { useCallback, useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Card, SectionHeader } from "../../ui/primitives";
import ResponsePlan from "./ResponsePlan";

const API_BASE_URL = (
  import.meta.env.VITE_API_BASE_URL || "http://localhost:9008"
).replace(/\/$/, "");

export default function TripResponsePage({
  token,
  user,
  initialTripPlan = "",
  onBackToPlanner,
}) {
  const [planResponse, setPlanResponse] = useState(initialTripPlan || "");
  const [lastPlanAt, setLastPlanAt] = useState(
    initialTripPlan?.trim() ? new Date().toISOString() : ""
  );
  const [isLoading, setIsLoading] = useState(false);
  const [loadError, setLoadError] = useState("");
  const [guideCompanion, setGuideCompanion] = useState(null);
  const [guideLoading, setGuideLoading] = useState(false);
  const [guideError, setGuideError] = useState("");

  const loadGuideCompanion = useCallback(async () => {
    if (!token) return;

    setGuideLoading(true);
    setGuideError("");

    try {
      const response = await fetch(
        `${API_BASE_URL}/api/v1/trip-planning/guide-companion`,
        {
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const payload = await response.json().catch(() => null);

      if (response.status === 404) {
        setGuideCompanion(null);
        setGuideError(
          "Guide Companion needs a generated trip plan first. Generate or refresh your plan."
        );
        return;
      }

      if (!response.ok) {
        throw new Error(
          payload?.message || "Failed to load guide companion insights"
        );
      }

      setGuideCompanion(payload?.data || null);
    } catch (error) {
      setGuideError(error.message || "Unable to load guide companion insights");
    } finally {
      setGuideLoading(false);
    }
  }, [token]);

  const loadTripResponses = useCallback(async () => {
    if (!token) return;

    setIsLoading(true);
    setLoadError("");

    try {
      const dashboardResponse = await fetch(
        `${API_BASE_URL}/api/v1/trip-planning/dashboard`,
        {
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const dashboardPayload = await dashboardResponse.json().catch(() => null);

      if (dashboardResponse.ok) {
        const planData = dashboardPayload?.data?.tripPlan || null;

        setPlanResponse(
          typeof planData?.response === "string" ? planData.response : ""
        );
        setLastPlanAt(
          typeof planData?.createdAt === "string" ? planData.createdAt : ""
        );
        return;
      }

      if (dashboardResponse.status === 404) {
        const latestResponse = await fetch(
          `${API_BASE_URL}/api/v1/trip-planning/latest`,
          {
            method: "GET",
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );

        const latestPayload = await latestResponse.json().catch(() => null);
        if (!latestResponse.ok && latestResponse.status !== 404) {
          throw new Error(
            latestPayload?.message || "Failed to load latest trip plan"
          );
        }

        setPlanResponse(
          typeof latestPayload?.data?.plan === "string"
            ? latestPayload.data.plan
            : ""
        );
        setLastPlanAt(
          typeof latestPayload?.data?.createdAt === "string"
            ? latestPayload.data.createdAt
            : ""
        );
        setLoadError(
          "Dashboard API not available yet on this backend instance. Showing trip plan only."
        );
        return;
      }

      throw new Error(
        dashboardPayload?.message || "Failed to load trip dashboard"
      );
    } catch (error) {
      setLoadError(error.message || "Unable to load trip responses");
    } finally {
      setIsLoading(false);
    }
  }, [token]);

  const refreshDashboard = useCallback(async () => {
    await Promise.all([loadTripResponses(), loadGuideCompanion()]);
  }, [loadGuideCompanion, loadTripResponses]);

  useEffect(() => {
    if (typeof initialTripPlan === "string" && initialTripPlan.trim()) {
      setPlanResponse(initialTripPlan);
      setLastPlanAt(new Date().toISOString());
    }
  }, [initialTripPlan]);

  useEffect(() => {
    loadTripResponses();
  }, [loadTripResponses]);

  useEffect(() => {
    loadGuideCompanion();
  }, [loadGuideCompanion]);

  return (
    <main className="min-h-screen px-4 py-6 sm:px-6 sm:py-8">
      <div className="mx-auto max-w-[1320px] space-y-6">
        <Card>
          <SectionHeader
            icon={
              <img
                src="/logo.png"
                alt="Wander logo"
                className="h-36 w-36 rounded-md object-contain"
              />
            }
            title="Wander"
            subtitle="Generated by Gemini 3. Dedicated dashboard for your saved trip-planning AI output."
            right={
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={onBackToPlanner}
                  className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--surface)] px-3 py-1.5 text-xs font-semibold text-[#35505c] transition hover:border-[var(--line-strong)] hover:bg-[#fff8eb]"
                >
                  <ArrowLeft className="h-3.5 w-3.5" />
                  Planner
                </button>
              </div>
            }
          />
        </Card>

        <ResponsePlan
          title="Wander"
          subtitle="Generated by Gemini 3 travel intelligence."
          planResponseText={planResponse}
          isLoading={isLoading}
          loadError={loadError}
          lastPlanAt={lastPlanAt}
          guideCompanion={guideCompanion}
          guideLoading={guideLoading}
          guideError={guideError}
          token={token}
          user={user}
          onRefresh={refreshDashboard}
        />
      </div>
    </main>
  );
}
